######
######

env {
  # You can set flink configuration here
  execution.parallelism = 1
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
  job.name="sss"
}

source {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**
  JdbcSourceStream{
    table_name="books"
    url="jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8"
    driver="com.mysql.jdbc.Driver"
    username="root"
    password="381079845"
    fetch_size="4"
    fields ="id,title,authors,years"
    result_table_name = "test"
    query="select id,title,authors,years from books"
  }

}

transform {

  #使用split函数(确认fake表存在)
  sql {
    sql = "select id,title,authors,years from test where id >107 "

        fields ="id,title,authors,years"
        result_table_name = "test2"
  }

  UdfSql {
      sql = "SELECT id, title, str_len(authors) AS description_length FROM test2 "
    }
}

sink {
FileSink {
       path="/Users/zhanghongmac/Downloads/flink/flink-waterdrop/config/writedir1"
         format="csv"
         write_mode="OVERWRITE"
  }
  ConsoleSink {}

}