######
###### This config file is a demonstration of batch processing in waterdrop config
######

env {
  # You can set flink configuration here
  execution.parallelism = 1
  job.name="batch-jdbc-test"
}

source {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**
  FileSource{
    path = "/Users/zhanghongmac/Downloads/flink/flink-waterdrop/config/test.csv"
    inputFormat="csv"
    format.type="csv"
    schema = "[{\"type\":\"Int\"},{\"type\":\"string\"},{\"type\":\"string\"},{\"type\":\"Int\"}]"
    result_table_name = "test"
    field_name="id,title,authors,years"
  }

  # If you would like to get more information about how to configure waterdrop and see full list of input plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}

transform {
    Split{
    separator = ","
    fields = ["id","title","authors","years"]
  }
  #使用split函数
  UdfSql {
    udfsql = "select id,title,authors,years from test"
  }
  # If you would like to get more information about how to configure waterdrop and see full list of filter plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}

sink {
  # Use our new JdbcBatchSink for batch processing
  JdbcBatchSink {
    url="jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8"
    driver="com.mysql.jdbc.Driver"
    password = "381079845"
    username = "root"
    query = "insert into books (id, title, authors, years) values (?, ?, ?, ?)"
  }

  # If you would like to get more information about how to configure waterdrop and see full list of output plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
} 