env {
 execution.parallelism = 1
  job.name="batch-jdbc-test"
}

source {
 JdbcSourceStream{
    table_name="spatial_data"
    url="jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8"
    driver="com.mysql.jdbc.Driver"
    username="root"
    password="381079845"
    fetch_size="4"
    fields ="id,location,geom1,geom2"
    result_table_name = "input_table"
    query="select id,location,geom1 from spatial_data"
  }
JdbcSourceStream{
    table_name="spatial_data"
    url="jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8"
    driver="com.mysql.jdbc.Driver"
    username="root"
    password="381079845"
    fetch_size="4"
    fields ="id,location,geom1,geom2"
    result_table_name = "input_table2"
    query="select id,location,geom2 from spatial_data"
  }
}

transform {
  Sql {
      fields ="id,location,geom1,geom2"
      result_table_name = "test2"
  sql = """
    SELECT
        input_table.id,
        input_table.location,
        input_table.geom1,
        input_table2.geom2
    FROM input_table
    LEFT JOIN input_table2
      ON input_table.id = input_table2.id
    WHERE input_table2.geom2 IS NOT NULL
  """
  }
  SpatialUdfRegister {}
  sql {
    source_table_name = "test2"
    sql = "SELECT id,location,geom1,geom2,st_intersects(geom1, geom2) AS is_intersecting FROM test2"
  }
}

#        st_intersects(geom1, geom2) AS is_intersecting
sink {
  ConsoleSink {}
}
