env {
  execution.parallelism = 1
  job.name = "Waterdrop UdfSql Transform Demo"
}

source {
  FileSource {
    path = "/Users/zhanghongmac/Downloads/flink/flink-waterdrop/config/input.csv"
    inputFormat = "csv"
    format.type = "csv"
    schema = "[{\"type\":\"Int\"},{\"type\":\"string\"},{\"type\":\"string\"}]"
    result_table_name = "input_table"
    field_name = "id,name,description"
  }
}

transform {
# 注册自定义UDF函数
  UdfSql {
    sql = "SELECT id, name, str_len(description) AS description_length FROM input_table WHERE id > 10"
  }
}

sink {
  ConsoleSink {}
} 