######
###### This config file is a demonstration of streaming processing in waterdrop config
######

env {
  # You can set flink configuration here
  execution.parallelism = 1
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
  job.name="sss"
}

source {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**
  JdbcSourceStream{
    table_name="book"
    url="jdbc:mysql://127.0.0.1:3306/mydb?characterEncoding=UTF-8"
    driver="com.mysql.jdbc.Driver"
    username="root"
    password="MyNewPass4!"
    fetch_size="4"
    fields ="id,title,authors,years"
    result_table_name = "test"
    query="select id,title,authors,years from book"
  }

  # If you would like to get more information about how to configure waterdrop and see full list of input plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}

transform {

  #使用split函数(确认fake表存在)
  sql {
    sql = "select id,title,authors,years from test"
  }
  # If you would like to get more information about how to configure waterdrop and see full list of filter plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}

sink {
//  ConsoleSink {}
  MyJdbcSink {
    url="jdbc:mysql://127.0.0.1:3306/mydb"
    driver="com.mysql.jdbc.Driver"
    password = "MyNewPass4!"
    username = "root"
    query = "insert into books (id, title, authors, years) values (?, ?, ?, ?)"
  }


  # If you would like to get more information about how to configure waterdrop and see full list of output plugins,
}